development:
  adapter: postgresql
  database: scheduler_app_development
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: scheduler_app_test
  

production:
  adapter: postgresql
  encoding: unicode
  database: scheduler_app_production
  
